In [ ]:
# THIS FILE TAKES Twitter accounts from each city, scrapes *all* of their tweets, and makes one big JSON file! 
# Then I have the code to convert to a dataframe,

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import json      # library for working with JSON-formatted text strings
import pprint as pp    # library for cleanly printing Python data structures
import seaborn as sns


# This is a basic test for https://github.com/taspinar/twitterscraper. Using the demo data looking at all tweets re. Trump. 

# twitterscraper "climate change from:metrolosangeles" --lang en -o cc_test.JSON -l 100

In [4]:
#FUNCTION JSON TO DATAFRAME
def json_to_df_tweets (csv_file):
    with open(csv_file) as f:
      data = json.load(f)
    
    d = {'username': [x['username'] for x in data],
        'time': [x['timestamp'] for x in data],
        'tweet': [x['text'] for x in data],
        'likes': [x['likes'] for x in data],
        'replies': [x['replies'] for x in data]
        }
    
    df_Test = pd.DataFrame.from_dict(d)
    
    return df_Test

In [7]:
# USE THIS ONE !!!!!!!!!!

#FUNCTION: TWITTERSCRAPER TO JSON file

#THIS IS THE ONE GOOD ONE WTIHOUT KEYWORDS - USE THIS ONE 

def twitterscraper(usernames, city):
    string = ' twitterscraper " '+ usernames+'" --lang en -o '+city+'.JSON' 
    return print(string)

def frommer(account):
    account = account.lower()
    string = 'OR from:'+account
    return print(string)

#FOR EACH CITY FOLLOW THESE STEPS TO MAKE 1 JSON FILE:

##### Step 1: frommer the twitter accounts 

for account in ["SeattleOPCD", "CityofSeattle", "seattledot", "SeattleOSE", "kcmetrobus"]:
    frommer(account)

##### Step 2 - update usernames w/frommer output

# usernames - use the frommer output cut & paste:
usernames = "from:seattleopcd OR from:cityofseattle OR from:seattledot OR from:seattleose OR from:kcmetrobus"   

##### Step 3 - twitterscraper them w/city name

twitterscraper(usernames, "seattle")


#OUTPUT SHOULD BE SOMETHING LIKE:
# twitterscraper " from:seattleopcd OR from:cityofseattle OR from:seattledot OR from:seattleose OR from:kcmetrobus" --lang en -o seattle---.JSON

### IMPORTANT - a space BEFORE the 'twitterscraper' in the CL seems important for some reason
## with this code, I got about 14k tweets!

OR from:seattleopcd
OR from:cityofseattle
OR from:seattledot
OR from:seattleose
OR from:kcmetrobus
 twitterscraper " from:seattleopcd OR from:cityofseattle OR from:seattledot OR from:seattleose OR from:kcmetrobus" --lang en -o seattle.JSON

In [9]:
# JSON TO DATAFRAME FUNCTION
seattle = json_to_df_tweets('seattle.JSON')
print(seattle)

seattle = seattle.loc[(seattle['tweet'].str.contains('COVID'))]
seattle

                       username                 time  \
0                    seattledot  2009-09-21T23:31:29
1                    seattledot  2009-09-21T23:18:02
2                    seattledot  2009-09-21T23:17:47
3                    seattledot  2009-09-21T22:53:49
4                    seattledot  2009-09-21T22:50:43
...                         ...                  ...
14262  King County Metro 🚏 🚌🚎⛴🚐  2015-04-17T16:55:34
14263                seattledot  2015-04-17T16:22:46
14264                seattledot  2015-04-17T16:22:10
14265                seattledot  2015-04-17T16:18:48
14266                seattledot  2015-04-17T16:02:59

                                                   tweet  likes  replies
0      The earlier vehicle collision on NB MLK at S B...      0        0
1      There is vehicle collision on NB MLK at S Bran...      0        0
2      The earlier vehicle collision at 12759 Rooseve...      0        0
3      There is vehicle collision at 12759 Roosevelt ...      0        0
4      Heads up! Lane closures on the Aurora Bridge a...      0        0
...                                                  ...    ...      ...
14262  @reedlyblue not sure how many miles in a day. ...      0        0
14263  Join SDOT Director Scott Kubly online Mon.4/20...      1        0
14264  @kptrease @skubly @UGreenways We'll ask our St...      2        1
14265  @natetepp Those poor bees. Fortunately no #Bee...      1        0
14266  Seeing congestion on I-5 NB and I-90 WB into S...      0        1

[14267 rows x 5 columns]

,username,time,tweet,likes,replies
291,King County Metro 🚏 🚌🚎⛴🚐,2020-04-02T23:00:43,Metro’s Thursday PM Commute: See Metro Matters...,2,1
293,King County Metro 🚏 🚌🚎⛴🚐,2020-04-02T22:00:59,Metro’s Thursday PM Commute: Reduced transit s...,0,0
301,King County Metro 🚏 🚌🚎⛴🚐,2020-04-02T16:01:04,Metro’s Thursday AM Commute: see Metro’s lates...,0,0
302,King County Metro 🚏 🚌🚎⛴🚐,2020-04-02T15:00:10,Metro’s Thursday AM Commute: see Metro’s lates...,2,0
306,King County Metro 🚏 🚌🚎⛴🚐,2020-04-02T14:00:08,Metro’s Thursday AM Commute: Reduced transit s...,2,0
...,...,...,...,...,...
582,King County Metro 🚏 🚌🚎⛴🚐,2020-03-24T20:45:54,A Metro employee shared on March 22 that they ...,23,1
627,King County Metro 🚏 🚌🚎⛴🚐,2020-03-23T22:01:32,Metro's Monday PM Commute: See Metro’s blog po...,0,3
645,King County Metro 🚏 🚌🚎⛴🚐,2020-03-23T16:01:26,Metro’s Monday AM Commute: Still no reported t...,0,0
646,seattledot,2020-03-23T16:00:13,We've seen how parking needs have changed duri...,38,5
649,King County Metro 🚏 🚌🚎⛴🚐,2020-03-23T15:10:45,Metro’s Monday AM Commute: Still no reported t...,1,0

In [16]:
# once we have all the cities, we could use this to combine all the cities into ONE BIG DATAFRAME 

def combine_dataframe (df1, df2, df3, df4, df5): #this function smooshes all the dataframes into one using .append()
    d1 = df1.append(df2)
    d2 = d1.append(df3)
    d3 = d2.append(df4)
    d4 = d3.append(df5)
    return d4.drop_duplicates(subset='tweet', keep="first") #the scraper picked up dups, this rectifies that

In [ ]:
"""
IGNORE FOR NOW MOSTLY, I don't know what this one is different but keeping it for a minute

FUNCTIONS

def twitterscraper(usernames, keywords, city):
    string = 'twitterscraper "'+ keywords+' '+usernames+'" --lang en -o '+city+'.JSON -l 1000' 
    return print(string)

def frommer(account):
    account = account.lower()
    string = 'OR from:'+account
    return print(string)

#FOR EACH CITY FOLLOW THESE STEPS TO MAKE 1 JSON FILE:

##### Step 1: frommer the twitter accounts 

for account in ["SeattleOPCD", "CityofSeattle", "seattledot", "SeattleOSE", "kcmetrobus"]:
    frommer(account)

##### Step 2 - update username/keywords 

# usernames - use the frommer output cut & paste:
usernames = "from:seattleopcd OR from:cityofseattle OR from:seattledot OR from:seattleose OR from:kcmetrobus"   

# same keywords everytime
keywords = "climate change OR global warming OR sea level rise OR greenhouse gas OR resilience OR sustainability OR sustainable OR carbon OR emissions"

##### Step 3 - twitterscraper them w/city name

twitterscraper(usernames, keywords, "seattle-3")

In [14]:
'''
#### ~~~~~~ DONT USE THIS ONE ANYMORE ~~~~~~~~

#FUNCTION: TWITTERSCRAPER TO JSON file

#  THIS IS THE ONE WTIH KEYWORDS 

def twitterscraper(usernames, keywords, city):
    string = 'twitterscraper "'+ keywords+' '+usernames+'" --lang en -o '+city+'.JSON' 
    return print(string)

def frommer(account):
    account = account.lower()
    string = 'OR from:'+account
    return print(string)

#FOR EACH CITY FOLLOW THESE STEPS TO MAKE 1 JSON FILE:

##### Step 1: frommer the twitter accounts 

for account in ["SeattleOPCD", "CityofSeattle", "seattledot", "SeattleOSE", "kcmetrobus"]:
    frommer(account)

##### Step 2 - update username/keywords 

# usernames - use the frommer output cut & paste:
#iesernames = "from:seattleopcd OR from:cityofseattle OR from:seattledot OR from:seattleose OR from:kcmetrobus"   

# NO KEYWORDS ANYMORE same keywords everytime
keywords = "climate change OR global warming OR sea level rise OR greenhouse gas OR resilience OR sustainability OR sustainable OR carbon OR emissions"

##### Step 3 - twitterscraper them w/city name

twitterscraper(usernames, keywords, "seattle-3")

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-14-090c2cf5f28d>, line 36)